alias dc='docker-compose'

alias dcb='docker-compose build'
alias dcr='docker-compose run --rm'
alias dcu='docker-compose up'
alias dcd='docker-compose kill && docker-compose down'
alias dcl='docker-compose logs -f --tail=100'
alias dcrs='docker-compose restart'
alias dck='docker-compose kill'
alias dca='docker-compose kill && docker-compose down && docker-compose up -d && autolog'

alias bc='docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.benchmark.yml'
alias bcb='bc build'
alias bcr='bc run --rm'
alias bcu='bc up'
alias bcd='bc kill && bc down'
alias bcl='bc logs'
alias bcrs='bc restart'
alias bck='bc kill'
alias bca='bc kill && bc down && bc up -d && autolog'

alias kb='kubectl'
alias kbg='kubectl get'
alias kbgp='kubectl get pods'
alias kbgd='kubectl get deployments.apps'
alias kbgs='kubectl get services'

alias skr='skaffold run'
alias skd='skaffold dev --cleanup=false'
