alias dc='docker-compose'

alias dcb='docker-compose build'
alias dcr='docker-compose run --rm'
alias dcu='docker-compose up'
alias dcd='docker-compose kill && docker-compose down'
alias dcl='docker-compose logs'
alias dcrs='docker-compose restart'
alias dck='docker-compose kill'
alias dca='docker-compose kill && docker-compose down && docker-compose up -d && autolog'
