#!/usr/bin/env python3 

from pathlib import Path

DOTFILES_DIR = Path(__file__).parents[1].resolve()
HOME_DIR = Path.home()

def iter_files():
    for f in DOTFILES_DIR.rglob('*.symlink'):
        yield f

for file_path in iter_files():
    symlink_name = file_path.stem
    symlink_dir = HOME_DIR / Path(*file_path.relative_to(DOTFILES_DIR).parts[1:-1])
    symlink_path = symlink_dir / symlink_name
    backup_path = symlink_dir / (symlink_name + '.backup')

    symlink_dir.mkdir(parents=True, exist_ok=True)
    
    if symlink_path.is_symlink():
        symlink_path.unlink()

    if symlink_path.exists():
        print('Backing up to {}'.format(backup_path))
        symlink_path.rename(backup_path)

    print('Creating symlink {} --> {}'.format(symlink_path, file_path))
    symlink_path.symlink_to(file_path)


